# Generated by Django 4.2.2 on 2023-08-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=150)),
                ("curp", models.TextField(max_length=18, unique=True)),
                ("tuition", models.TextField(max_length=20, unique=True)),
                ("email", models.TextField(max_length=100, unique=True)),
                ("isAdmin", models.BooleanField(default=False)),
            ],
        ),
    ]
