# Generated by Django 4.2.2 on 2023-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=150)),
                ("curp", models.TextField(max_length=18, unique=True)),
                ("tuition", models.TextField(max_length=20, unique=True)),
                ("email", models.TextField(max_length=100, unique=True)),
                ("password", models.TextField(max_length=100)),
                ("role", models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
